services:
    okvpn_warmup_cache.configuration_loader:
        class: Okvpn\Bundle\WarmupCacheBundle\Cache\ConfigurationLoader
        calls:
            - [ setParameterBag, ['@=service("kernel").getContainer().getParameterBag()']]

    okvpn_warmup_cache.dumper:
        class: Oro\Component\Config\Dumper\CumulativeConfigMetadataDumper
        public: false
        arguments:
            - '%kernel.cache_dir%'
            - '%kernel.debug%'
            - 'oro_action'

    okvpn_warmup_cache.lisener.cache_waramer:
        class: Okvpn\Bundle\WarmupCacheBundle\EventListener\CacheWarmerListener
        arguments:
            - '%kernel.debug%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: checkCache }
            - { name: kernel.event_listener, event: console.command, method: checkCache }
